.segment "RODATA1"
logo_tiles:       .incbin "data/logo.pix"

.segment "RODATA2"
logo_map:         .incbin "data/logo.map"
logo_palette:     .incbin "data/logo.pal"
wario_tiles:      .incbin "data/wario.pix"
wario_palette:    .incbin "data/wario.pal"
level_tiles:      .incbin "data/level1.pix"
level1_palette:   .incbin "data/level1.pal"
level1_map:       .incbin "data/level1_map.map"
level1_collision: .incbin "data/level1_collision.col"
level2_palette:   .incbin "data/level2.pal"
level2_map:       .incbin "data/level2_map.map"
level2_collision: .incbin "data/level2_collision.col"
level3_palette:   .incbin "data/level3.pal"
level3_map:       .incbin "data/level3_map.map"
level3_collision: .incbin "data/level3_collision.col"

.segment "RODATA3"
level4_palette:   .incbin "data/level4.pal"
level4_map:       .incbin "data/level4_map.map"
level4_collision: .incbin "data/level4_collision.col"
level5_palette:   .incbin "data/level5.pal"
level5_map:       .incbin "data/level5_map.map"
level5_collision: .incbin "data/level5_collision.col"
level6_palette:   .incbin "data/level6.pal"
level6_map:       .incbin "data/level6_map.map"
level6_collision: .incbin "data/level6_collision.col"
level7_palette:   .incbin "data/level7.pal"
level7_map:       .incbin "data/level7_map.map"
level7_collision: .incbin "data/level7_collision.col"
level8_palette:   .incbin "data/level8.pal"
level8_map:       .incbin "data/level8_map.map"
level8_collision: .incbin "data/level8_collision.col"
